apiVersion: v1
kind: Service
metadata:
  name: vnext-cancer-detect
  namespace: ${NAMESPACE}
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: vnext-cancer-detect
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vnext-cancer-detect
  namespace: ${NAMESPACE}
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: vnext-cancer-detect
  template:
    metadata:
      labels:
          app: vnext-cancer-detect
          azure.workload.identity/use: "true"
    spec:
      serviceAccountName: ${NAMESPACE}-pod-identity
      nodeSelector:
        agentpool: apps
      containers:
        - name: vnext-cancer-detect
          image: CONTAINER_IMAGE
          resources:
            requests:
              cpu: ${REQUEST_CPU}
              memory: ${REQUEST_MEMORY}
            limits:
              cpu: ${LIMITS_CPU}
              memory: ${LIMITS_MEMORY}
          securityContext:
            privileged: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 3000
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: vnext-cancer-detect-hpa
  namespace: ${NAMESPACE}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vnext-cancer-detect
  minReplicas: ${MIN_REPLICAS}
  maxReplicas: ${MAX_REPLICAS}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: ${AVERAGE_CPU_UTILIZATION}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: ${AVERAGE_MEMORY_UTILIZATION}

